"""Prerender the Dutch version of index.html and producten.html into the page itself.

The site renders with React at runtime (support.js), so readers without JavaScript
(AI crawlers, read-page, no-JS visitors) only saw the raw {{ t.x }} template. This
script opens each page in headless Chrome in Dutch at desktop width, takes the
rendered #dc-root and writes it between the prerender markers as normal, visible
HTML. The template itself sits in <template data-dc-template>, so nothing renders
it and text readers skip it. support.js mounts React into that same element, so it simply replaces the
prerender with the live page (in the visitor's language).

Run after every change to page copy, prices, packages or FAQ:

    python prerender.py

Needs Playwright (pip install playwright) and Chrome.
"""
import functools
import http.server
import re
import socketserver
import sys
import threading
from pathlib import Path

from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parent
PAGES = ["index.html", "producten.html"]
START = "<!-- prerender:start (generated by prerender.py, do not edit by hand) -->"
END = "<!-- prerender:end -->"


def serve():
    class Quiet(http.server.SimpleHTTPRequestHandler):
        def log_message(self, *args):
            pass

    handler = functools.partial(Quiet, directory=str(ROOT))
    httpd = socketserver.TCPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd


def render(browser, url, source):
    ctx = browser.new_context(locale="nl-BE", viewport={"width": 1280, "height": 900})
    page = ctx.new_page()
    errors = []
    page.on("pageerror", lambda e: errors.append(str(e)))
    page.goto(url, wait_until="load")
    page.wait_for_function(
        "() => { const r = document.getElementById('dc-root');"
        " return r && r.children.length && !r.innerText.includes('{{'); }",
        timeout=20000,
    )
    page.wait_for_timeout(500)
    html, styles = page.evaluate(
        """() => [document.getElementById('dc-root').innerHTML,
                  [...document.head.querySelectorAll('style')].map(s => s.textContent)]"""
    )
    ctx.close()
    # The auto-scrolling photo rails move every frame; store them at their start position.
    html = re.sub(r"transform: translate3d\(-?[\d.]+px, 0px, 0px\)", "transform: translate3d(0px, 0px, 0px)", html)
    if errors:
        sys.exit(f"{url}: page error while rendering: {errors[0]}")
    # Keep the styles the runtime put in <head> (page CSS from the template included);
    # styles already in the source <head> apply before JavaScript anyway.
    head = source.split("</head>", 1)[0]
    runtime_css = [s for s in styles if s.strip() and s not in head]
    return html, runtime_css


def main():
    httpd = serve()
    port = httpd.server_address[1]
    with sync_playwright() as p:
        try:
            browser = p.chromium.launch(channel="chrome")
        except Exception:
            browser = p.chromium.launch()
        for name in PAGES:
            path = ROOT / name
            src = path.read_text(encoding="utf-8")
            # Compare against the page without an old prerender, or its styles would count as source.
            bare = re.sub(re.escape(START) + r".*?" + re.escape(END), "", src, flags=re.S)
            html, css = render(browser, f"http://127.0.0.1:{port}/{name}", bare)
            if "{{" in html or "</x-dc>" in html:
                sys.exit(f"{name}: render still contains template markup, not writing")
            style = "".join(f"<style>{re.sub(r'/[*].*?[*]/', '', c, flags=re.S)}</style>" for c in css)
            block = f'{START}\n<div id="dc-prerender">{style}{html}</div>\n{END}'
            if START in src:
                new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block, src, flags=re.S)
            else:
                if src.count("</x-dc>") != 1:
                    sys.exit(f"{name}: expected exactly one </x-dc>")
                new = src.replace("</x-dc>", "</x-dc>\n" + block, 1)
            nl = "\r\n" if "\r\n" in src else "\n"
            new = new.replace("\r\n", "\n").replace("\n", nl)
            path.write_text(new, encoding="utf-8", newline="")
            print(f"{name}: prerendered {len(html) // 1024} KiB, {len(css)} runtime style block(s)")
        browser.close()
    httpd.shutdown()


if __name__ == "__main__":
    main()
